language: go

go:
  - "1.12.x"


os:
  - linux

branches:
  only:
    - master
    - develop


services:
  - mysql


matrix:
  fast_finish: true
  include:
    - go: 1.12.x
      env: GO111MODULE=on

install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; else go get -t -v ./...; fi

before_install:
  # TRAVIS_OS_NAME - linux and osx
  - echo $TRAVIS_OS_NAME
  - echo $PATH
  - mysql -u root < deploy/sql/travis_test.sql
#  - |
#    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
#      brew update && brew install redis && brew services start redis && brew install mysql && brew services start mysql
#    fi
#  - |
#    brew install mysql && brew services start mysql

script:
  - go test -v ./...